/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#7f2b05",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#f8bd42",
        "tertiary-container": "#926900",
        "on-tertiary-container": "#fff4e6",
        "inverse-on-surface": "#fbeee8",
        "secondary-fixed": "#c9e6ff",
        "on-surface": "#201a17",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#56423b",
        "tertiary-fixed": "#ffdea5",
        "outline-variant": "#ddc1b7",
        "on-secondary": "#ffffff",
        "secondary": "#466176",
        "inverse-primary": "#ffb59b",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fff3ef",
        "surface-dim": "#e3d8d1",
        "error-container": "#ffdad6",
        "on-secondary-container": "#4a667b",
        "primary-fixed-dim": "#ffb59b",
        "surface-container-highest": "#ece0da",
        "on-secondary-fixed-variant": "#2e4a5e",
        "on-primary": "#ffffff",
        "surface-tint": "#9e421c",
        "surface-variant": "#ece0da",
        "surface-bright": "#fff8f5",
        "primary-fixed": "#ffdbcf",
        "background": "#fff8f5",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#5d4200",
        "secondary-container": "#c6e3fc",
        "secondary-fixed-dim": "#adcae2",
        "surface-container-high": "#f2e6df",
        "surface-container": "#f8ece5",
        "primary-container": "#b5532c",
        "on-tertiary-fixed": "#271900",
        "primary": "#953c16",
        "on-background": "#201a17",
        "on-secondary-fixed": "#001e2f",
        "surface-container-low": "#fef1eb",
        "on-error": "#ffffff",
        "surface": "#fff8f5",
        "outline": "#89726a",
        "tertiary": "#735200",
        "inverse-surface": "#362f2b",
        "on-primary-fixed": "#380d00"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "max-width": "1200px",
        "base": "8px",
        "gutter": "16px",
        "margin-mobile": "20px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-sm": ["Bricolage Grotesque", "sans-serif"],
        "headline-lg-mobile": ["Bricolage Grotesque", "sans-serif"],
        "body-md": ["Source Serif 4", "serif"],
        "body-lg": ["Source Serif 4", "serif"],
        "label-md": ["Courier Prime", "monospace"],
        "headline-lg": ["Bricolage Grotesque", "sans-serif"],
        "headline-md": ["Bricolage Grotesque", "sans-serif"],
        "label-lg": ["Courier Prime", "monospace"]
      },
      fontSize: {
        "headline-sm": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
